// This file is auto-generated by `b10cks generate types`. Do not edit manually.

export interface B10cksItem {
  id: string
  block: string
}

/** WCAG contrast stats derived from the asset's dominant color. */
export interface B10cksAssetA11y {
  /** 'dark' = treat the image as a dark surface (use light overlays/text). */
  scheme: 'dark' | 'light'
  /** WCAG relative luminance of the dominant color (0–1). */
  luminance: number
  /** Contrast ratio of white text against the dominant color (1–21). */
  contrast_white: number
  /** Contrast ratio of black text against the dominant color (1–21). */
  contrast_black: number
}

/** A generated video preview frame. */
export interface B10cksAssetThumbnail {
  path: string
  full_path?: string
  /** Frame position in seconds. */
  position: number
  /** Frame position as mm:ss / hh:mm:ss. */
  position_formatted: string
  /** Dominant color of this frame as #rrggbb. */
  dominant_color?: string
}

/** EXIF subset extracted from JPEG/TIFF uploads. */
export interface B10cksAssetExif {
  make?: string | null
  model?: string | null
  exposure?: string | number | null
  aperture?: string | number | null
  iso?: string | number | null
  dateTaken?: string | null
  orientation?: number | null
}

/** ID3-style tags extracted from audio uploads. */
export interface B10cksAssetMediaTags {
  title?: string | null
  artist?: string | null
  album?: string | null
  year?: string | null
  genre?: string | null
}

/**
 * Metadata extracted from an asset at upload time. Which fields are present
 * depends on the file type (image, video, audio, document). Custom metadata
 * supplied at upload is carried through via the index signature.
 */
export interface B10cksAssetMetadata {
  type?: 'image' | 'video' | 'audio' | 'document' | 'file'
  /** Format refinement, e.g. 'svg', 'pdf' or the source mime type. */
  subtype?: string
  original_filename?: string
  width?: number
  height?: number
  /** width / height, rounded to 4 decimals. */
  aspectRatio?: number
  /** Dominant color as #rrggbb — usable as a loading placeholder. */
  dominant_color?: string
  /** Up to 5 representative colors, most dominant first (palette[0] === dominant_color). */
  palette?: string[]
  /** True for multi-frame GIF/WebP images. */
  animated?: boolean
  a11y?: B10cksAssetA11y
  exif?: B10cksAssetExif
  /** Duration in seconds (video/audio). */
  duration?: number
  fps?: number
  bitrate?: number
  codec?: string
  thumbnails?: B10cksAssetThumbnail[]
  channels?: number
  sample_rate?: number
  tags?: B10cksAssetMediaTags
  [key: string]: unknown
}

export type B10cksAsset = {
    url: string
    data: Record<string, unknown>
    metadata: B10cksAssetMetadata,
    id: string
    size: number
    type: "asset"
    filename: string
    extension: string
    full_path: string
    mime_type: string
}

export type B10cksLink = {
  url: string;
  type: 'url'
  target?: '_self' | '_blank' | '_parent' | '_top'
  rel?: string
} | {
  type: 'email'
  email: string
  subject?: string
  body?: string
  cc?: string
  bcc?: string
} | {
  type: 'internal'
  url: string
  title: string
  content: string
  params?: string
  target?: '_self' | '_blank' | '_parent' | '_top'
} | {
  type: 'asset'
  id: string
}

export interface B10cksRichTextMark {
  type: string
  attrs?: Record<string, unknown>
}

export interface B10cksRichTextNode {
  type: string
  attrs?: Record<string, unknown>
  content?: B10cksRichTextNode[]
  marks?: B10cksRichTextMark[]
  text?: string
}

export interface B10cksRichText {
  type: 'doc'
  content?: B10cksRichTextNode[]
}

export type B10cksMeta = {
  title?: string
  description?: string
  canonical?: string
  robots?: string
  ogTitle?: string
  ogDescription?: string
  ogImage?: B10cksAsset | null
}

export type B10cksTableCell = string | number | boolean | null

export interface B10cksTableRow {
  id: string
  cells: Record<string, B10cksTableCell>
}

export interface B10cksTable {
  header: Record<string, string>
  rows: B10cksTableRow[]
}

export type B10cksPrice = Record<string, number | null>

export interface B10cksMenu extends B10cksItem {
  items?: B10cksMenuitem[]
  title?: string
}

export interface B10cksMenuitem extends B10cksItem {
  link?: B10cksLink
  label?: string
}

export interface B10cksButton extends B10cksItem {
  link?: B10cksLink
  size?: 'default' | 'xs' | 'sm' | 'lg'
  label?: string
  variant: 'default' | 'primary' | 'accent' | 'outline' | 'ghost' | 'link'
  disabled?: boolean
}

export interface B10cksConfig extends B10cksItem {
  actions?: B10cksButton[]
  mainMenu?: B10cksMenuitem[]
  siteName?: string
  copyright?: string
  footerMenu?: B10cksMenu[]
  footerText?: string
}

export interface B10cksPage extends B10cksItem {
  body?: B10cksItem[]
  meta?: B10cksMeta
}

export interface B10cksError extends B10cksItem {
  body?: B10cksItem[]
}
